### ISSUE TITLE
Есть предложение по сотрудничеству 

### ISSUE THREAD

**Issue by Msk009** [VladiStep/instagram_parser#1]
Есть интересный проект по Инсте. Рынок - весь мир.
К сожалению, интересы разработчика с которым начинали проект у нас разошлись.
А проект уже начал свой коммерческий путь.
Если вам интересно было бы обсудить возможные варианты сотрудничества, то как с вами связаться?

**Comment by VladiStep** [comment]
По почте, указанной в моём профиле - [vlad2001.21@mail.ru](mailto:vlad2001.21@mail.ru)
